### ISSUE TITLE
Generate FLIX 1.0.0 format

### ISSUE THREAD

**Issue by bthaile** [onflow/flixkit-go#18]
Given a transaction or script in Cadence generate FLIX format 1.0.0

 - [x] Use cadence comment header for all properties
 - [x] Fill in Dependences, support multiple ways smart contracts can include dependencies 
  - import contract with address
  - new import syntax that relies on flow.json
  - old import syntax that uses placeholder)
 - [x] Fill in Parameters
 - [x] Fill in all Messages and support languages
 - [x] Build hashes. See, generating FLIX has to know about pinning hash (See in fcl)
https://github.com/onflow/fcl-js/blob/master/packages/fcl/src/interaction-template-utils/generate-dependency-pin.js

This functionality will not provide prompting the user, all data needs to be provided in comment blocks and flow.json

 - [ ] Test import syntax
    - string import
    - old import with placeholder
    - import with address

**Comment by bjartek** [comment]
I have a lot of this code in overflow already. Feel free to copy it over. https://github.com/bjartek/overflow/blob/flix2/flix.go and related files
