### ISSUE TITLE
[BUG] Improper import alias replacements on execution (or generation)

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flixkit-go#85]
### Current Behavior

Executing [this generated template](https://github.com/onflow/batched-evm-exec-example/blob/gio/add-flix/cadence/flix/wrap_and_mint.flix.json) (generated with `flow flix generate ...`) results in error 

```sh
error: unexpected token in import declaration: got decimal integer, expected string, address, or identifier
 --> :3:16
  |
3 | import EVM from 8c5303eaa26202d6
```

Updating the template at [line 683](https://github.com/onflow/batched-evm-exec-example/blob/gio/add-flix/cadence/flix/wrap_and_mint.flix.json#L683C1-L683C63) from

```json
"address": "8c5303eaa26202d6",
```
to 

```json
"address": "0x8c5303eaa26202d6",
```

results in successful execution. This makes me think that the error lies in how the aliased imports are replaced.

### Expected Behavior

I would expect the generated template to execute successfully

### Steps To Reproduce

From a project root with a Testnet address properly configured and funded from Faucet, run

```sh
flow flix execute https://raw.githubusercontent.com/onflow/batched-evm-exec-example/refs/heads/gio/add-flix/cadence/flix/wrap_and_mint.flix.json \
  0xd3bF53DAC106A0290B0483EcBC89d40FcC961f3e \
  0xdbC43Ba45381e02825b14322cDdd15eC4B3164E6 \
  --signer testnet-signer \
  -n testnet
```

And you'll see the reported error
  

### Environment

```markdown
- OS: MacOS Sonoma 14.7
- Flow CLI: v2.0.10
```

### What are you currently working on that this is blocking?

Generating a FLIX template for [this example repo](https://github.com/onflow/batched-evm-exec-example/tree/gio/add-flix)

**Comment by bthaile** [comment]
Thanks for reporting. The issue is contract dependencies are passed in based on flow.json. These addresses are missing "0x" prefix. flixkit needs to verify dependency addresses are formatted correctly to be used to replace "string" imports.
